### ISSUE TITLE
Better handling of attribute defaults

### ISSUE THREAD

**Issue by vegu** [20c/confu#31]
> if you have a ConfigSchema, it has a default, then it creates argparse with a default
> so you can't tell if the value passed is actually passed in, or just left blank

There currently is an issue where default's cannot be reasonably determined in a setup that uses schema for cli arguments as well as config data objects.

**Comment by egfrank** [comment]
Okay pushed again for the apply_argparse changes we were talking about:
https://github.com/20c/confu/pull/37/commits/f26c6da2ebebb6aa2d3806a8d96a57a2bcfdb1a4
