### ISSUE TITLE
Github workflow for linting (flake8, black, isort) and testing

### ISSUE THREAD

**Issue by vegu** [20c/confu#38]
Github workflow for linting (`flake8`, `black`, `isort`) and testing, can look [here](https://github.com/20c/ctl/blob/master/.github/workflows/tests.yml) for an example.

Remove travis config

Also fix `flake8` issues if there are any. Lets discuss things like "function too complex" prior to implementation changes though.

All tests currently pass, so that should also be the case after these changes.

**Comment by egfrank** [comment]
I made these changes on `gh_39` 

https://github.com/20c/confu/pull/42
